// Simple NCERT Question Generator
// Auto-generates high-quality questions based on NCERT syllabus

export interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  chapter: string;
  subject: string;
  class: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  questionType: 'MCQ' | 'Numerical' | 'Conceptual';
  ncertReference: string;
  marks: number;
}

// Question templates for different subjects
const questionTemplates = {
  Physics: [
    "The SI unit of {quantity} is?",
    "Which of the following is a fundamental physical quantity?",
    "The dimensional formula of {concept} is?",
    "The slope of velocity-time graph gives?",
    "A particle moves with uniform acceleration. The relation between velocity and displacement is?",
    "The work done by force {force} over distance {distance} is?",
    "The kinetic energy of a particle of mass {mass} moving with velocity {velocity} is?",
    "The potential energy at height {height} with mass {mass} is?",
    "The momentum of a particle with mass {mass} and velocity {velocity} is?",
    "The frequency of a wave with wavelength {wavelength} and velocity {velocity} is?",
    "The period of a simple pendulum of length {length} is?",
    "The electric field at distance {distance} from charge {charge} is?",
    "The magnetic field due to current {current} at distance {distance} is?",
    "The resistance of a wire with resistivity {resistivity}, length {length} and area {area} is?",
    "The capacitance of a parallel plate capacitor with area {area} and separation {separation} is?"
  ],
  Chemistry: [
    "The number of moles in {mass}g of {substance} is?",
    "Which of the following has maximum number of molecules?",
    "The molarity of a solution containing {amount} moles in {volume}L is?",
    "Which of the following is a colligative property?",
    "The rate of reaction depends on?",
    "The pH of a solution with [H+] = {concentration} M is?",
    "The equilibrium constant for reaction {reaction} is?",
    "The oxidation state of {element} in {compound} is?",
    "The hybridization of {molecule} is?",
    "The bond angle in {molecule} is approximately?",
    "The enthalpy change for reaction {reaction} is?",
    "The entropy change for process {process} is?",
    "The Gibbs free energy change for reaction {reaction} at temperature {temperature} is?",
    "The solubility product of {compound} is?",
    "The electrode potential for {half-cell} is?"
  ],
  Mathematics: [
    "If A = {setA} and B = {setB}, then A × B contains how many elements?",
    "The domain of function f(x) = {function} is?",
    "The value of integral of {function} is?",
    "The probability of event {event} is?",
    "The solution of equation {equation} is?",
    "The derivative of function f(x) = {function} is?",
    "The limit of function {function} as x approaches {value} is?",
    "The sum of series {series} is?",
    "The value of permutation {permutation} is?",
    "The value of combination {combination} is?",
    "The area under curve y = {function} from {a} to {b} is?",
    "The volume generated by rotating {curve} about {axis} is?",
    "The solution of differential equation {equation} is?",
    "The value of determinant {determinant} is?",
    "The inverse of matrix {matrix} is?"
  ],
  Biology: [
    "The {organelle} is responsible for {cellFunction} in the cell?",
    "Which of the following is a characteristic of {organism}?",
    "The {bioProcess} occurs in which part of the cell?",
    "The {enzyme} catalyzes the conversion of {substrate} to {product}?",
    "The {structure} in {organ} performs {cellFunction}?",
    "The {cycle} consists of {number} stages?",
    "The {system} in humans includes which of the following?",
    "The {disease} is caused by deficiency of {nutrient}?",
    "The {trait} is inherited through which pattern?",
    "The {organism} belongs to which kingdom?",
    "The {bioProcess} in plants occurs during which phase?",
    "The {bioMolecule} is synthesized in which organelle?",
    "The {reaction} in {pathway} requires which cofactor?",
    "The {hormone} regulates which physiological process?",
    "The {tissue} is composed of which type of cells?"
  ]
};

// Variables for question generation
const variables = {
  // Physics variables
  quantity: ["length", "mass", "time", "temperature", "electric current", "luminous intensity", "amount of substance"],
  concept: ["force", "pressure", "energy", "power", "momentum", "impulse", "work", "torque"],
  force: [10, 20, 50, 100, 200],
  distance: [5, 10, 20, 50, 100],
  velocity: [5, 10, 20, 50, 100],
  height: [10, 20, 50, 100, 200],
  wavelength: [400, 500, 600, 700, 800],
  length: [1, 2, 5, 10, 20],
  charge: [1, 2, 5, 10, 20],
  current: [1, 2, 5, 10, 20],
  resistivity: [1.1, 2.3, 5.6, 10.5, 20.8],
  area: [1, 2, 5, 10, 20],
  separation: [0.1, 0.2, 0.5, 1, 2],
  
  // Chemistry variables
  mass: [2, 4, 8, 16, 32],
  substance: ["hydrogen", "oxygen", "nitrogen", "carbon dioxide", "water", "methane"],
  amount: [0.1, 0.2, 0.5, 1, 2],
  volume: [1, 2, 5, 10, 20],
  concentration: [0.001, 0.01, 0.1, 1, 10],
  reaction: ["A + B -> C", "2A + B -> C", "A -> B + C", "A + B -> C + D"],
  element: ["carbon", "oxygen", "nitrogen", "hydrogen", "sulfur"],
  compound: ["CO2", "H2O", "NH3", "CH4", "NaCl"],
  molecule: ["methane", "water", "ammonia", "carbon dioxide", "ethane"],
  process: ["dissolution", "evaporation", "condensation", "sublimation"],
  temperature: [273, 298, 373, 473, 573],
  halfCell: ["Cu²+/Cu", "Zn²+/Zn", "Fe³+/Fe²+", "Ag+/Ag"],
  
  // Mathematics variables
  setA: ["{1,2,3,4}", "{a,b,c}", "{x,y,z}", "{1,2,3}", "{0,1,2,3}"],
  setB: ["{3,4,5,6}", "{d,e,f}", "{p,q,r}", "{4,5,6}", "{4,5,6,7}"],
  function: ["1/(x-2)", "x²+1", "sin(x)", "log(x)", "e^x", "sqrt(x)", "1/x"],
  event: ["getting a head", "drawing a red card", "rolling a 6", "selecting a prime", "getting an even number"],
  equation: ["x²+1=0", "2x+3=7", "x²-4=0", "3x-2=10", "x³-8=0", "sin(x)=0"],
  value: [0, 1, 2, 3, 4],
  series: ["1+2+3+...+n", "1²+2²+...+n²", "1/2+1/4+...+1/2^n", "n+(n+1)+(n+2)"],
  permutation: ["5P3", "10P4", "7P2", "6P6"],
  combination: ["5C3", "10C4", "7C2", "6C3"],
  a: [0, 1, 2, 3, 4],
  b: [1, 2, 3, 4, 5],
  curve: ["y=x²", "y=sin(x)", "y=e^x", "y=1/x"],
  axis: ["x-axis", "y-axis", "z-axis"],
  determinant: ["|1 2; 3 4|", "|2 1; 1 2|", "|3 4; 5 6|"],
  matrix: ["[[1,2],[3,4]]", "[[2,0],[0,2]]", "[[1,0],[0,1]]"],
  
  // Biology variables
  organelle: ["mitochondria", "nucleus", "ribosome", "chloroplast", "endoplasmic reticulum"],
  cellFunction: ["ATP production", "DNA storage", "protein synthesis", "photosynthesis", "lipid synthesis"],
  organism: ["bacteria", "virus", "fungi", "plant", "animal"],
  bioProcess: ["photosynthesis", "respiration", "digestion", "circulation", "excretion"],
  enzyme: ["amylase", "lipase", "protease", "DNA polymerase", "ATP synthase"],
  substrate: ["starch", "lipids", "proteins", "nucleotides", "ADP"],
  product: ["glucose", "fatty acids", "amino acids", "DNA", "ATP"],
  structure: ["heart", "brain", "liver", "kidney", "lung"],
  organ: ["heart", "brain", "liver", "kidney", "lung"],
  cycle: ["cell cycle", "Krebs cycle", "Calvin cycle", "menstrual cycle"],
  number: [2, 3, 4, 5, 6],
  system: ["digestive system", "respiratory system", "circulatory system", "nervous system", "excretory system"],
  disease: ["scurvy", "rickets", "anemia", "beriberi", "pellagra"],
  nutrient: ["vitamin C", "vitamin D", "iron", "thiamine", "niacin"],
  trait: ["eye color", "blood type", "height", "skin color", "hair texture"],
  kingdom: ["Monera", "Protista", "Fungi", "Plantae", "Animalia"],
  phase: ["day", "night", "interphase", "mitosis", "meiosis"],
  bioMolecule: ["DNA", "RNA", "protein", "ATP", "glucose"],
  pathway: ["glycolysis", "Krebs cycle", "electron transport chain", "Calvin cycle"],
  cofactor: ["NAD+", "FAD", "CoA", "ATP", "GTP"],
  hormone: ["insulin", "glucagon", "thyroxine", "adrenaline", "estrogen"],
  tissue: ["muscle tissue", "nervous tissue", "connective tissue", "epithelial tissue", "vascular tissue"]
};

// Generate options for different question types
function generateOptions(questionType: string, correctAnswer: string): string[] {
  const commonOptions = [
    correctAnswer,
    "Option B (Incorrect)",
    "Option C (Incorrect)", 
    "Option D (Incorrect)"
  ];
  
  // Shuffle options
  return commonOptions.sort(() => Math.random() - 0.5);
}

// Generate a single question
function generateSingleQuestion(
  subject: string,
  chapter: string,
  classYear: string,
  index: number
): Question {
  const templates = questionTemplates[subject as keyof typeof questionTemplates] || questionTemplates.Physics;
  const template = templates[index % templates.length];
  
  // Replace variables in template
  let questionText = template;
  Object.keys(variables).forEach(key => {
    const values = variables[key as keyof typeof variables];
    const value = values[Math.floor(Math.random() * values.length)];
    questionText = questionText.replace(new RegExp(`{${key}}`, 'g'), value.toString());
  });
  
  const correctAnswer = "Option A (Correct)";
  const options = generateOptions(template, correctAnswer);
  const correctIndex = options.indexOf(correctAnswer);
  
  return {
    id: `${subject}-${chapter}-${index}`,
    question: questionText,
    options,
    correctAnswer: correctIndex,
    explanation: `This question is based on NCERT ${classYear} ${subject} Chapter: ${chapter}`,
    chapter,
    subject,
    class: classYear,
    difficulty: index % 3 === 0 ? 'Easy' : index % 3 === 1 ? 'Medium' : 'Hard',
    questionType: 'MCQ',
    ncertReference: `NCERT ${classYear} ${subject} Chapter ${chapter}`,
    marks: 1
  };
}

// Generate questions for a chapter
export function generateQuestionsForChapter(
  subject: string,
  chapter: string,
  classYear: string,
  count: number = 50
): Question[] {
  const questions: Question[] = [];
  
  for (let i = 0; i < count; i++) {
    const question = generateSingleQuestion(subject, chapter, classYear, i);
    questions.push(question);
  }
  
  return questions;
}

// Generate questions for multiple chapters
export function generateQuestionsForChapters(
  chapters: { name: string; subject: string; class: string }[],
  questionsPerChapter: number = 50
): Question[] {
  const allQuestions: Question[] = [];
  
  chapters.forEach(chapter => {
    const questions = generateQuestionsForChapter(
      chapter.subject,
      chapter.name,
      chapter.class,
      questionsPerChapter
    );
    allQuestions.push(...questions);
  });
  
  return allQuestions;
}

// Get random questions from generated pool
export function getRandomQuestions(
  questions: Question[],
  count: number,
  difficulty?: 'Easy' | 'Medium' | 'Hard'
): Question[] {
  let filteredQuestions = questions;
  
  if (difficulty) {
    filteredQuestions = questions.filter(q => q.difficulty === difficulty);
  }
  
  // Shuffle and take required count
  const shuffled = [...filteredQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Generate complete NCERT question database (20K questions)
export function generateNCERTQuestionDatabase(): Question[] {
  const allQuestions: Question[] = [];
  
  // Engineering syllabus chapters
  const engineeringChapters = [
    // Physics 11th
    { name: 'Physical World & Measurement', subject: 'Physics', class: '11th' },
    { name: 'Kinematics', subject: 'Physics', class: '11th' },
    { name: 'Laws of Motion', subject: 'Physics', class: '11th' },
    { name: 'Work, Energy & Power', subject: 'Physics', class: '11th' },
    { name: 'Rotational Motion', subject: 'Physics', class: '11th' },
    { name: 'Gravitation', subject: 'Physics', class: '11th' },
    { name: 'Properties of Solids & Liquids', subject: 'Physics', class: '11th' },
    { name: 'Thermodynamics', subject: 'Physics', class: '11th' },
    { name: 'Kinetic Theory of Gases', subject: 'Physics', class: '11th' },
    { name: 'Oscillations & Waves', subject: 'Physics', class: '11th' },
    
    // Physics 12th
    { name: 'Electric Charges and Fields', subject: 'Physics', class: '12th' },
    { name: 'Electrostatic Potential and Capacitance', subject: 'Physics', class: '12th' },
    { name: 'Current Electricity', subject: 'Physics', class: '12th' },
    { name: 'Moving Charges and Magnetism', subject: 'Physics', class: '12th' },
    { name: 'Magnetism and Matter', subject: 'Physics', class: '12th' },
    { name: 'Electromagnetic Induction', subject: 'Physics', class: '12th' },
    { name: 'Alternating Current', subject: 'Physics', class: '12th' },
    { name: 'Electromagnetic Waves', subject: 'Physics', class: '12th' },
    { name: 'Ray Optics and Optical Instruments', subject: 'Physics', class: '12th' },
    { name: 'Wave Optics', subject: 'Physics', class: '12th' },
    { name: 'Dual Nature of Radiation and Matter', subject: 'Physics', class: '12th' },
    { name: 'Atoms', subject: 'Physics', class: '12th' },
    { name: 'Nuclei', subject: 'Physics', class: '12th' },
    { name: 'Semiconductor Electronics: Materials, Devices and Simple Circuits', subject: 'Physics', class: '12th' },
    
    // Chemistry 11th
    { name: 'Some Basic Concepts of Chemistry', subject: 'Chemistry', class: '11th' },
    { name: 'Structure of Atom', subject: 'Chemistry', class: '11th' },
    { name: 'Periodic Table & Periodicity', subject: 'Chemistry', class: '11th' },
    { name: 'Chemical Bonding', subject: 'Chemistry', class: '11th' },
    { name: 'Thermodynamics', subject: 'Chemistry', class: '11th' },
    { name: 'Equilibrium', subject: 'Chemistry', class: '11th' },
    { name: 'Redox Reactions', subject: 'Chemistry', class: '11th' },
    { name: 'p-Block Elements', subject: 'Chemistry', class: '11th' },
    { name: 'Organic Chemistry Basics', subject: 'Chemistry', class: '11th' },
    { name: 'Hydrocarbons', subject: 'Chemistry', class: '11th' },
    
    // Chemistry 12th
    { name: 'Solutions', subject: 'Chemistry', class: '12th' },
    { name: 'Electrochemistry', subject: 'Chemistry', class: '12th' },
    { name: 'Chemical Kinetics', subject: 'Chemistry', class: '12th' },
    { name: 'd- and f-Block Elements', subject: 'Chemistry', class: '12th' },
    { name: 'Coordination Compounds', subject: 'Chemistry', class: '12th' },
    { name: 'Haloalkanes and Haloarenes', subject: 'Chemistry', class: '12th' },
    { name: 'Alcohols, Phenols and Ethers', subject: 'Chemistry', class: '12th' },
    { name: 'Aldehydes, Ketones and Carboxylic Acids', subject: 'Chemistry', class: '12th' },
    { name: 'Amines', subject: 'Chemistry', class: '12th' },
    { name: 'Biomolecules', subject: 'Chemistry', class: '12th' },
    
    // Mathematics 11th
    { name: 'Sets, Relations & Functions', subject: 'Mathematics', class: '11th' },
    { name: 'Complex Numbers & Quadratics', subject: 'Mathematics', class: '11th' },
    { name: 'Permutations & Combinations', subject: 'Mathematics', class: '11th' },
    { name: 'Binomial Theorem', subject: 'Mathematics', class: '11th' },
    { name: 'Sequence & Series', subject: 'Mathematics', class: '11th' },
    { name: 'Straight Lines', subject: 'Mathematics', class: '11th' },
    { name: 'Conic Sections', subject: 'Mathematics', class: '11th' },
    { name: 'Limits & Derivatives', subject: 'Mathematics', class: '11th' },
    { name: 'Statistics', subject: 'Mathematics', class: '11th' },
    
    // Mathematics 12th
    { name: 'Relations and Functions', subject: 'Mathematics', class: '12th' },
    { name: 'Inverse Trigonometric Functions', subject: 'Mathematics', class: '12th' },
    { name: 'Matrices', subject: 'Mathematics', class: '12th' },
    { name: 'Determinants', subject: 'Mathematics', class: '12th' },
    { name: 'Continuity and Differentiability', subject: 'Mathematics', class: '12th' },
    { name: 'Application of Derivatives', subject: 'Mathematics', class: '12th' },
    { name: 'Integrals', subject: 'Mathematics', class: '12th' },
    { name: 'Application of Integrals', subject: 'Mathematics', class: '12th' },
    { name: 'Differential Equations', subject: 'Mathematics', class: '12th' },
    { name: 'Vector Algebra', subject: 'Mathematics', class: '12th' },
    { name: 'Three Dimensional Geometry', subject: 'Mathematics', class: '12th' },
    { name: 'Linear Programming', subject: 'Mathematics', class: '12th' },
    { name: 'Probability', subject: 'Mathematics', class: '12th' }
  ];

  // Medical syllabus chapters (Biology focused)
  const medicalChapters = [
    // Physics 11th (Medical)
    { name: 'Physical World & Measurement', subject: 'Physics', class: '11th' },
    { name: 'Kinematics', subject: 'Physics', class: '11th' },
    { name: 'Laws of Motion', subject: 'Physics', class: '11th' },
    { name: 'Work, Energy & Power', subject: 'Physics', class: '11th' },
    { name: 'Rotational Motion', subject: 'Physics', class: '11th' },
    { name: 'Gravitation', subject: 'Physics', class: '11th' },
    { name: 'Properties of Solids & Liquids', subject: 'Physics', class: '11th' },
    { name: 'Thermodynamics', subject: 'Physics', class: '11th' },
    { name: 'Kinetic Theory of Gases', subject: 'Physics', class: '11th' },
    { name: 'Oscillations & Waves', subject: 'Physics', class: '11th' },
    
    // Physics 12th (Medical)
    { name: 'Electric Charges and Fields', subject: 'Physics', class: '12th' },
    { name: 'Electrostatic Potential and Capacitance', subject: 'Physics', class: '12th' },
    { name: 'Current Electricity', subject: 'Physics', class: '12th' },
    { name: 'Moving Charges and Magnetism', subject: 'Physics', class: '12th' },
    { name: 'Magnetism and Matter', subject: 'Physics', class: '12th' },
    { name: 'Electromagnetic Induction', subject: 'Physics', class: '12th' },
    { name: 'Alternating Current', subject: 'Physics', class: '12th' },
    { name: 'Electromagnetic Waves', subject: 'Physics', class: '12th' },
    { name: 'Ray Optics and Optical Instruments', subject: 'Physics', class: '12th' },
    { name: 'Wave Optics', subject: 'Physics', class: '12th' },
    { name: 'Dual Nature of Radiation and Matter', subject: 'Physics', class: '12th' },
    { name: 'Atoms', subject: 'Physics', class: '12th' },
    { name: 'Nuclei', subject: 'Physics', class: '12th' },
    { name: 'Semiconductor Electronics: Materials, Devices and Simple Circuits', subject: 'Physics', class: '12th' },
    
    // Chemistry 11th (Medical)
    { name: 'Some Basic Concepts of Chemistry', subject: 'Chemistry', class: '11th' },
    { name: 'Structure of Atom', subject: 'Chemistry', class: '11th' },
    { name: 'Periodic Table & Periodicity', subject: 'Chemistry', class: '11th' },
    { name: 'Chemical Bonding', subject: 'Chemistry', class: '11th' },
    { name: 'Thermodynamics', subject: 'Chemistry', class: '11th' },
    { name: 'Equilibrium', subject: 'Chemistry', class: '11th' },
    { name: 'Redox Reactions', subject: 'Chemistry', class: '11th' },
    { name: 'p-Block Elements', subject: 'Chemistry', class: '11th' },
    { name: 'Organic Chemistry Basics', subject: 'Chemistry', class: '11th' },
    { name: 'Hydrocarbons', subject: 'Chemistry', class: '11th' },
    
    // Chemistry 12th (Medical)
    { name: 'Solutions', subject: 'Chemistry', class: '12th' },
    { name: 'Electrochemistry', subject: 'Chemistry', class: '12th' },
    { name: 'Chemical Kinetics', subject: 'Chemistry', class: '12th' },
    { name: 'd- and f-Block Elements', subject: 'Chemistry', class: '12th' },
    { name: 'Coordination Compounds', subject: 'Chemistry', class: '12th' },
    { name: 'Haloalkanes and Haloarenes', subject: 'Chemistry', class: '12th' },
    { name: 'Alcohols, Phenols and Ethers', subject: 'Chemistry', class: '12th' },
    { name: 'Aldehydes, Ketones and Carboxylic Acids', subject: 'Chemistry', class: '12th' },
    { name: 'Amines', subject: 'Chemistry', class: '12th' },
    { name: 'Biomolecules', subject: 'Chemistry', class: '12th' },
    
    // Biology 11th (Medical)
    { name: 'The Living World', subject: 'Biology', class: '11th' },
    { name: 'Biological Classification', subject: 'Biology', class: '11th' },
    { name: 'Plant Kingdom', subject: 'Biology', class: '11th' },
    { name: 'Animal Kingdom', subject: 'Biology', class: '11th' },
    { name: 'Morphology of Flowering Plants', subject: 'Biology', class: '11th' },
    { name: 'Anatomy of Flowering Plants', subject: 'Biology', class: '11th' },
    { name: 'Structural Organisation', subject: 'Biology', class: '11th' },
    { name: 'Cell: The Unit of Life', subject: 'Biology', class: '11th' },
    { name: 'Biomolecules (11th)', subject: 'Biology', class: '11th' },
    { name: 'Cell Cycle and Division', subject: 'Biology', class: '11th' },
    { name: 'Photosynthesis', subject: 'Biology', class: '11th' },
    { name: 'Respiration in Plants', subject: 'Biology', class: '11th' },
    { name: 'Plant Growth', subject: 'Biology', class: '11th' },
    { name: 'Breathing & Exchange', subject: 'Biology', class: '11th' },
    { name: 'Body Fluids & Circulation', subject: 'Biology', class: '11th' },
    { name: 'Excretory Products', subject: 'Biology', class: '11th' },
    { name: 'Locomotion & Movement', subject: 'Biology', class: '11th' },
    { name: 'Neural Control', subject: 'Biology', class: '11th' },
    { name: 'Chemical Coordination', subject: 'Biology', class: '11th' },
    
    // Biology 12th (Medical)
    { name: 'Reproduction in Organisms', subject: 'Biology', class: '12th' },
    { name: 'Sexual Reproduction in Plants', subject: 'Biology', class: '12th' },
    { name: 'Human Reproduction', subject: 'Biology', class: '12th' },
    { name: 'Reproductive Health', subject: 'Biology', class: '12th' },
    { name: 'Principles of Inheritance', subject: 'Biology', class: '12th' },
    { name: 'Molecular Basis of Inheritance', subject: 'Biology', class: '12th' },
    { name: 'Evolution', subject: 'Biology', class: '12th' },
    { name: 'Human Health & Disease', subject: 'Biology', class: '12th' },
    { name: 'Microbes in Human Welfare', subject: 'Biology', class: '12th' },
    { name: 'Biotechnology: Principles', subject: 'Biology', class: '12th' },
    { name: 'Biotechnology Applications', subject: 'Biology', class: '12th' },
    { name: 'Organisms & Populations', subject: 'Biology', class: '12th' },
    { name: 'Ecosystem', subject: 'Biology', class: '12th' },
    { name: 'Biodiversity & Conservation', subject: 'Biology', class: '12th' }
  ];
  
  // Combine all chapters
  const allChapters = [...engineeringChapters, ...medicalChapters];
  
  // Generate questions for each chapter (100 questions per chapter)
  const questionsPerChapter = 100;
  
  allChapters.forEach(chapter => {
    const questions = generateQuestionsForChapter(
      chapter.subject,
      chapter.name,
      chapter.class,
      questionsPerChapter
    );
    allQuestions.push(...questions);
  });
  
  // Return exactly 20,000 questions
  return allQuestions.slice(0, 20000);
}

// Save question database to localStorage
export function saveQuestionDatabase(questions: Question[]): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem('ncertQuestionDatabase', JSON.stringify(questions));
  }
}

// Load question database from localStorage
export function loadQuestionDatabase(): Question[] {
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('ncertQuestionDatabase');
    if (stored) {
      return JSON.parse(stored);
    }
  }
  return [];
}

// Initialize question database if not exists
export function initializeQuestionDatabase(): Question[] {
  let questions = loadQuestionDatabase();
  
  if (questions.length === 0) {
    questions = generateNCERTQuestionDatabase();
    saveQuestionDatabase(questions);
  }
  
  return questions;
}
